#!/bin/bash

time_limit=3
program=./main
hash_table_size=12582917
thread_count=4

run_program()
{
	$program tsplib/$1.sop $time_limit $hash_table_size full $thread_count > tsplib_result/$1.txt
}

run_program br17.10
run_program br17.12

run_program ESC07
run_program ESC11
run_program ESC12
run_program ESC25
run_program ESC47
run_program ESC63
run_program ESC78

run_program ft53.1
run_program ft53.2
run_program ft53.3
run_program ft53.4
run_program ft70.1
run_program ft70.2
run_program ft70.3
run_program ft70.4

run_program rbg048a
run_program rbg050c
run_program rbg109a
run_program rbg150a
run_program rbg174a
run_program rbg253a
run_program rbg323a
run_program rbg341a
run_program rbg358a
run_program rbg378a

run_program kro124p.1
run_program kro124p.2
run_program kro124p.3
run_program kro124p.4

run_program p43.1
run_program p43.2
run_program p43.3
run_program p43.4

run_program prob.100
run_program prob.42

run_program ry48p.1
run_program ry48p.2
run_program ry48p.3
run_program ry48p.4

