#!/bin/bash

time_limit=600
program=./main
hash_table_size=12582917
thread_count=4

echo "instance,static_lower_bound,nearest_neighbor_cost,best_solution_cost,time(sec),enumerated0,enumerated1,enumerated2,enumerated3,bounds0,bounds1,bounds2,bounds3" > mibench_result/all_results.csv
run_program()
{
	str="$($program mibench/$1.sop $time_limit $hash_table_size $thread_count)"
	str="$1,$str"
	echo "$str" >> mibench_result/all_results.csv
}

run_program gsm.153.124
run_program gsm.444.350
run_program gsm.462.77
sleep 120

run_program jpeg.1483.25
run_program jpeg.3184.107
run_program jpeg.3195.85
run_program jpeg.3198.93
sleep 120
run_program jpeg.3203.135
run_program jpeg.3740.15
run_program jpeg.4154.36
run_program jpeg.4753.54
sleep 120

run_program susan.248.197
run_program susan.260.158
run_program susan.343.182
sleep 120

run_program typeset.10192.123
sleep 120
run_program typeset.10835.26
run_program typeset.12395.43
run_program typeset.15087.23
run_program typeset.15577.36
sleep 120
run_program typeset.16000.68
run_program typeset.1723.25
run_program typeset.19972.246
run_program typeset.4391.240
run_program typeset.4597.45
sleep 120
run_program typeset.4724.433
run_program typeset.5797.33
run_program typeset.5881.246

