#!/bin/bash

time_limit=3
program=./test

run_program()
{
	$program mibench/$1.sop $time_limit > mibench_result/$1.txt
}

run_program gsm.153.124
run_program gsm.444.350
run_program gsm.462.77
run_program jpeg.1483.25
run_program jpeg.3184.107
run_program jpeg.3195.85
run_program jpeg.3198.93
run_program jpeg.3203.135
run_program jpeg.3740.15
run_program jpeg.4154.36
run_program jpeg.4753.54
run_program susan.248.197
run_program susan.260.158
run_program susan.343.182
run_program typeset.10835.26
run_program typeset.12395.43
run_program typeset.15087.23
run_program typeset.15577.36
run_program typeset.16000.68
run_program typeset.1723.25
run_program typeset.19972.246
run_program typeset.4391.240
run_program typeset.4597.45
run_program typeset.4724.433
run_program typeset.5797.33
run_program typeset.5881.246

